// <auto-generated />
namespace Glossary.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GlossaryEntity_Add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GlossaryEntity_Add));
        
        string IMigrationMetadata.Id
        {
            get { return "201705211124407_GlossaryEntity_Add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
